package handmadehttp

type Method string

var (
	ReqMethodGet Method = "GET"
)

const (
	MaxChanSize = 1000
)

const (
	DefaultProtocal    = "HTTP/1.1"
	DefaultContentType = "TEXT/HTML; CHARSET=UTF-8"
	BuffSize           = 1024
	MaxHeaderLine      = 1024

	KeyContentType   = "CONTENT-TYPE"
	KeyContentLength = "CONTENT-LENGTH"

	LineBreak = "\r\n"
)

var CodeToStatus = map[int]string{
	100: "CONTINUE",
	101: "SWITCHING PROTOCOLS",
	200: "OK",
	201: "CREATED",
	202: "ACCEPTED",
	203: "NON-AUTHORITATIVE INFORMATION",
	204: "NO CONTENT",
	205: "RESET CONTENT",
	206: "PARTIAL CONTENT",
	300: "MULTIPLE CHOICES",
	301: "MOVED PERMANENTLY",
	302: "FOUND",
	303: "SEE OTHER",
	304: "NOT MODIFIED",
	305: "USE PROXY",
	307: "TEMPORARY REDIRECT",
	400: "BAD REQUEST",
	401: "UNAUTHORIZED",
	402: "PAYMENT REQUIRED",
	403: "FORBIDDEN",
	404: "NOT FOUND",
	405: "METHOD NOT ALLOWED",
	406: "NOT ACCEPTABLE",
	407: "PROXY AUTHENTICATION REQUIRED",
	408: "REQUEST TIME-OUT",
	409: "CONFLICT",
	410: "GONE",
	411: "LENGTH REQUIRED",
	412: "PRECONDITION FAILED",
	413: "REQUEST ENTITY TOO LARGE",
	414: "REQUEST-URI TOO LARGE",
	415: "UNSUPPORTED MEDIA TYPE",
	416: "REQUESTED RANGE NOT SATISFIABLE",
	417: "EXPECTATION FAILED",
	500: "INTERNAL SERVER ERROR",
	501: "NOT IMPLEMENTED",
	502: "BAD GATEWAY",
	503: "SERVICE UNAVAILABLE",
	504: "GATEWAY TIME-OUT",
	505: "HTTP VERSION NOT SUPPORTED",
}
